language: python
python:
    - "3.5"
    - "3.6"
install:
  - pip install pipenv --upgrade-strategy=only-if-needed
  - pipenv install --dev --skip-lock
script:
  - pipenv run coverage run run.py
after_success:
  - pipenv run coveralls
